### PR TITLE
docs: add example template

### PR DESCRIPTION
**Pull request by CatStark**
After last meeting with @FionnD and @aga11313 , what you think about having a template for examples too? I made a PR already for the Fashion-MNIST to see how it should look.

### CODE REVIEW

**Comment by FionnD** [comment]
Hey @theUnkownName 

Yes! We had thought about it as well, this was our iteration from a while ago. Your is very similar to what we thought,  just a couple of extra sections. What do you think?  

# Overview
Include a dataset, what happens etc. 

# Deploy with Docker 
For a one line deployment, check out docker instructions here 

Pre requirements:
1. You have Docker installed and working 
2. You have at least 8GB of free space on your hard drive.

Step 1 blah 
 
# Deploy with Python
Step 1. Install 
Step 2. Build the app and index 
Step 3. Query with JinaBox 
Step 4. Query with CURL 

# Overview of the files
data/core/ - contains stories for Rasa Core
data/nlu_data.md - contains example NLU training data
actions.py - contains custom action/api code
domain.yml - the domain file for Core
nlu_config.yml - the NLU config file
core_config.yml - the Core config file
credentials.yml - contains credentials for the use with Telegram
endpoints.yml - contains url for endpoint

# Flow Diagram 
Similar to the one in the pdf example 

# Next steps
Link to ‘My first Jina app’
Link to ‘Adding your own data in Jina’ etc 

# Community
Slack channel - a communication platform for developers to discuss Jina
Community newsletter - subscribe to the latest update, release and event news of Jina
LinkedIn - get to know Jina AI as a company and find job opportunities
Twitter Follow - follow us and interact with us using hashtag #JinaSearch
Company - know more about our company, we are fully committed to open-source!

# License
Copyright (c) 2021 Jina AI Limited. All rights reserved.

Jina is licensed under the Apache License, Version 2.0. See LICENSE for the full license text.

**Comment by FionnD** [comment]
I also guess the template should live in the example repo

**Comment by CatStark** [comment]
Ah I didn't know we had a template already. But that one still looks very focused on Docker and other tools and not so much on Jina right? Maybe we should combine them?

**Comment by FionnD** [comment]
> Ah I didn't know we had a template already. But that one still looks very focused on Docker and other tools and not so much on Jina right? Maybe we should combine them?

We don't, it was just some ideas I and Agnes had seen in other companies (Rasa etc). I see your point, so you don't think we should include Docker run instructions in the examples at all?

**Comment by CatStark** [comment]
This was moved to examples [repo](https://github.com/jina-ai/examples/pull/497)

**Pull request closed without merging**
