### PR TITLE
fix(exit): correct links

### PR DESCRIPTION
**Pull request by alexcg1**
### All Submissions:

* [ ] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [ ] Have you added your new file to a table of content index? 
2. [ ] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [ ] Is your title in Title Case? 
4. [ ] Are your section headers in sentence case?

### CODE REVIEW

**Review by FionnD — APPROVED** [review]

**Comment by alexcg1** [comment]
wtf? I fix the links and linkcheck fails? Can someone look into this or should I just merge? (It's failing right at the end, on the line `	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)` of the Makefile, and not giving informative error msg at all

**Comment by FionnD** [comment]
@bwanglzu  ⏫  can you help @alexcg1

**Comment by bwanglzu** [comment]
@alexcg1 @FionnD search `broken` in CI, you'll find 2 broken links
image

**Comment by alexcg1** [comment]
`make linkcheck` fails on `cli/exit.rst` on my local machine when I test this branch. But actually testing it in the browser works perfectly (unlike pre-fix which was broken but I guess passed the tests?)

I'm very confused :confused: Can someone check my link syntax? While the syntax actually does work in real world, maybe it's not officially supported and thus fails the tests?

**Comment by alexcg1** [comment]
I mean, I could just merge this, sure. But then we'll have this broken linkcheck problem for everything else

**Comment by bwanglzu** [comment]
@alexcg1 one moment, I'm checking on my machine

**Comment by bwanglzu** [comment]
image
failed to run linkcheck locally

**Comment by alexcg1** [comment]
@bwanglzu actually test it in your browser. I can guarantee it really does work!

**Comment by bwanglzu** [comment]
@alexcg1 you're right, somehow the linkcheck failed while the link is correct..it's wired, might be a bug inside linkcheck module in sphinx

**Comment by bwanglzu** [comment]
@alexcg1 can you modify `conf.py` and add `101` and `102` into `linkcheck_ignore`? let's ignore this two links for the time being

**Comment by alexcg1** [comment]
> @alexcg1 can you modify `conf.py` and add `101` and `102` into `linkcheck_ignore`? let's ignore this two links for the time being

Done @bwanglzu

**Review by bwanglzu — APPROVED** [review]
lgtm!

**Pull request merged**
