### PR TITLE
fix(api-reference): correct singular-plural

### PR DESCRIPTION
**Pull request by alexcg1**
Previous: "API references"
Now: "API reference" (correct English)

### All Submissions:

* [ ] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [ ] Have you added your new file to a table of content index? 
2. [ ] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [ ] Is your title in Title Case? 
4. [ ] Are your section headers in sentence case?

### CODE REVIEW

**Comment by FionnD** [comment]
For Core, there is many API(s) so plural is correct right?

**Comment by alexcg1** [comment]
It's a reference to many APIs. The problem wasn't with the word API. The problem was pluralizing "reference"

**Comment by FionnD** [comment]
> It's a reference to many APIs. The problem wasn't with the word API. The problem was pluralizing "reference"

Ah of course, sorry

**Review by FionnD — APPROVED** [review]

**Comment by alexcg1** [comment]
I've checked linkcheck logs and they're once again claiming an external link is broken (404) when it's clearly not. Will go ahead and merge

**Pull request merged**
