### PR TITLE
fix: issue creation link in readme

### PR DESCRIPTION
**Pull request by shivaylamba**
### All Submissions:

* [x] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)?  

## Description
Fixed link for creation of new issue in Readme of docs.

### CODE REVIEW

**Comment by bwanglzu** [comment]
hi @shivaylamba please check my comment in #179 :)

**Review by bwanglzu — APPROVED** [review]
LGTM!

**Comment by shivaylamba** [comment]
I have changed the content @bwanglzu

**Comment by bwanglzu** [comment]
@FionnD since this PR only fix a link without touching the content, I'll merge it direcly.

**Pull request merged**
