### PR TITLE
docs(rest): updated for rest gateway

### PR DESCRIPTION
**Pull request by deepankarm**
### All Submissions:

* [x] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [x] Have you added your new file to a table of content index? 
2. [x] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [x] Is your title in Title Case? 
4. [ ] Are your section headers in sentence case?

### CODE REVIEW

**Comment by deepankarm** [comment]
I can't figure out the header font sizes for rst. Subsections are of the size of title :/

**Comment by FionnD** [comment]
Hey @deepankarm 
Thanks for doing this :) 

Does this document explain how to do CRUD operations via the REST API?

**Comment by rutujasurve94** [comment]
@deepankarm the headers can be changed with `#` (title), `##` (subtitle), `###` (sub sub section), etc. by adding it to the beginning of the line.
@FionnD the `curl` commands here have the `url` and `request` headers (should be sufficient for `REST API` usage)

**Comment by deepankarm** [comment]
@FionnD yah. Please refer [here](https://deploy-preview-227--jina-docs.netlify.app/chapters/rest/). 
There are quite a few things that would still need clarity as Jina relies on bytes for many fields & with JSON, we need to look at how to send bytes properly (e.g.- what encoding, how do we convert them in Document, how we stream using WebSockets etc). This PR removes the wrong information from before. 

@rutujasurve94 Is that true for rST files too?

**Comment by deepankarm** [comment]
Closes https://github.com/jina-ai/jina/issues/2090

**Review by FionnD — APPROVED** [review]

**Pull request merged**
