### PR TITLE
docs: improve seo

### PR DESCRIPTION
**Pull request by ThePfarrer**
#91 
- Added a robot.txt file as seen [here](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file)
- Added direct link to standard Jina commit message format

### CODE REVIEW

**Comment by FionnD** [comment]
Thanks for the PR @ThePfarrer 

@bwanglzu  can you make sure the robot is pointing to our default branch? See here https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file

**Review by nan-wang — CHANGES_REQUESTED** [review]
hi, @ThePfarrer Many thanks for your contribution. However, adding `robots.txt` won't have any effect. `robots.txt` should be place under `dos.jina.ai/robots.txt` according to https://developers.google.com/search/reference/robots_txt#examples-of-valid-robots.txt-urls. The HTML files are generated from this repo and later published to `gh_page` branch. You can find the doc generating script at https://github.com/jina-ai/docs/blob/master/.github/scripts/make-doc.sh and the github action at https://github.com/jina-ai/docs/blob/master/.github/workflows/cd.yml

**Comment by ThePfarrer** [comment]
@nan-wang thanks for the feedback. I will have a look.

**Comment by bwanglzu** [comment]
@ThePfarrer let me know if you have any questions

**Comment by florian-hoenicke** [comment]
related pr
https://github.com/jina-ai/docs/pull/141

**Comment by bwanglzu** [comment]
I would like to close this one since it has been resolved in #141 , still thanks so much @ThePfarrer !

**Pull request closed without merging**
