### PR TITLE
fix(wording): in the cloud to on the cloud

### PR DESCRIPTION
**Pull request by alexcg1**
We use "on the cloud" not "in the cloud". I've corrected all instances

- docs(my_first_app): initial commit
- fix(all): wording: in the cloud to on the cloud

### All Submissions:

* [ ] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [ ] Have you added your new file to a table of content index? 
2. [ ] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [ ] Is your title in Title Case? 
4. [ ] Are your section headers in sentence case?

### CODE REVIEW

**Comment by bwanglzu** [comment]
hi @alexcg1 , a minor remind
> According to official github documentation, Assignee is a person who is working on specific issues and pull requests.

So you should set yourself as assignee, and @FionnD as reviewer :)

**Comment by alexcg1** [comment]
Roger that @bwanglzu !

**Comment by FionnD** [comment]
LGTM, while you are here could you also add it to the style guide please ;)

**Review by FionnD — APPROVED** [review]

**Comment by alexcg1** [comment]
@FionnD https://github.com/jina-ai/docs/pull/113

**Pull request merged**
