### PR TITLE
docs: create new layout  for docs repo

### PR DESCRIPTION
**Pull request by FionnD**
**Purpose**: To reformat the layout of docs.jina.ai to the agreed-upon [new structure ](https://docs.google.com/document/d/1ntTSsbUiKA5mvc-Lsm-MyuAUbUXRs_l2F6i_1IeMNB4/edit#)

**Biggest concern is introducing breaking changes.** 

To do:
- [x] Someone to check that none of the existing pages have been lost in reordering 
- [x] Will the sphinx-argparse command line inline features still work? (For pages like hello world & Jina Command-Line Interface)
- [x] Will pseudomuto/protoc-gen-doc still work for both Jina API & Protobuf pages?

### CODE REVIEW

**Comment by FionnD** [comment]
@bwanglzu Tomorrow or Friday, could you take some time to answer the two **To do:** above, please?

**Comment by bwanglzu** [comment]
For question 2:
>  Will pseudomuto/protoc-gen-doc still work for both Jina API & Protobuf pages?

Yes, it will still work, it's automatically generated. If we only touch the way how it's structured, the content will remain the same

**Comment by bwanglzu** [comment]
Question 1
> Will the sphinx-argparse command line inline features still work? (For pages like hello world & Jina Command-Line Interface)

Same as above, it's linked to our jina via sphinx command, changing the layout won't affect the content!

**Review by bwanglzu — APPROVED** [review]
great work @FionnD ! it looks good to me, a lot of work! Let's merge it before the rest of the document being merged to avoid conflicts.

**Comment by bwanglzu** [comment]
please do squash and merge so that we have clear git history, checkout [this](https://softwareengineering.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests)
image

**Pull request merged**
