### PR TITLE
docs: improve chapters folder

### LINKED ISSUE #87: Improve chapters folder.
**Currently**: 
Our chapters folder has some files directly stored in chapters: `chapters/pod_page.md`
and some in their own folders: `chapters/pod_page/index.md`

In certain cases, this is to allow for local images to be stored in the chapter, but no always. 

**Problems**: 
1. Inconsistent file naming affects SEO. 
2. Confusion for new developers adding files. 
3. Images will be duplicated across folders. (Two folders using the same image). 
4. [Does not follow best web design practice](https://webstyleguide.com/wsg3/5-site-structure/3-site-file-structure.html) 

**Solution**: 
1. Create a folder for images `chapters/images/`
2. Move all images (.png/.gif etc) to that folder. 
3. Move all files to the root of the chapter folder. A file like `chapters/pods/pod_page.md` should be moved to `chapters/pod_page.md`. This might require renaming some files. 
4. When a file has been moved, the TOC should be updated. 
3. Update all files in the chapter folder so images are correctly shown. For example, a which has `.. image:: magnetic-balls.jpg `should be updated to `.. image:: ../images/magnetic-balls.jpg`

### PR DESCRIPTION
**Pull request by ThePfarrer**
As part of issue #87

- moved all images from `chapters/101`, `chapters/102`, and `chapters/helloworld` to `chapters/images`.
- moved the individual index files from the folders above to the root `chapters` folder.
- renamed the index files by prepending the folder name to the index file. Example `chapters/101/index.rst` becomes `chapters/101_index.rst` etc.
- updated TOC to reflect the changes made.

### CODE REVIEW

**Comment by FionnD** [comment]
Hi @alexcg1 
Can you please review / weight in on this? 

This will improve SEO, but break our links to 102/101. Is it worth it?

**Comment by bwanglzu** [comment]
in general I like the idea of putting all resource files such as images into the same place.

**Review by pswu11 — CHANGES_REQUESTED** [review]
Hello @ThePfarrer 
Could you use the naming 

- 101.rst instead of 101_index.rst
- 102.rst instead of 102_index.rst

Just to make the url shorter & cleaner. Thanks!

**Comment by ThePfarrer** [comment]
It will be nice to know how this can/will be resolved because it will lay the foundation for the rest of the issue.

Another thing that might be good to look at is having a standard naming convention. `hyphens` vs `underscores` for compound file names etc.

**Comment by FionnD** [comment]
A couple of points I have learned with web page naming: 

- The name should be human-readable. about_pods.html, not ap.html. 
- Underscores are more commonly used than hyphens. 
- Lowercase all letters. 
- Only letters (a-z). No numbers or symbols 

I agree 101 is then 101_index. Index implies it is a TOC page, which it is not. 

It will have to be a case-by-case basis going forward. Otherwise a good PR

**Comment by pswu11** [comment]
@FionnD Good points! It would be cool if you could provide some examples of good naming in the original issue or in our docs instruction. So the external contributor could follow them easily.

**Comment by alexcg1** [comment]
@ThePfarrer thanks for the contribution! Could you also ensure all links to 101/102/etc are updated to reflect your changes in the PR?

(Note: if it were me I'd run something like the following)

`grep -r chapters\/101\/index.rst docs | wc -l` <- this will search through all files in docs and check if they have the path to old 101 in them. Then it'll tell you how many need to be fixed

There's probably a global search/replace in your editor as well. Or you can use `sed` or `awk` or something similar from command line

**Comment by ThePfarrer** [comment]
Thanks  @pswu11 @FionnD @alexcg1, I will make the necessary corrections.

**Review by pswu11 — APPROVED** [review]
LGTM

**Comment by FionnD** [comment]
DO NOT MERGE 

I will need to review this PR later today, please do not merge yet :)

**Comment by bwanglzu** [comment]
please resolve the conflict

**Review by FionnD — APPROVED** [review]
This looks good to me. Thanks for taking the time to complete the issue, it's a very useful long term fix for Jina docs :) 

- [ ] As Bo mentioned the conflicts must be fixed. 

- [ ] @alexcg1 is currently fixing the 101 links. This must be done before this PR can be merged. He will update here when he is done. 

Once this PR is merged and deployed, it will be important to QA check that the live site dose not have broken links.

**Comment by alexcg1** [comment]
Check:
- https://github.com/jina-ai/jina/pull/1965
- https://github.com/jina-ai/docs/pull/107

These fix all 101 links in core and docs repos

**Comment by ThePfarrer** [comment]
@bwanglzu @FionnD I wasn't sure about the best way to resolve the conflict, so I did a `rebase` and `push --force-with-lease`. I will appreciate suggestions on better ways to handle this in the future.

**Comment by FionnD** [comment]
ha good question @ThePfarrer , rebasing is tough. Often you can rebase and see the differences in your IDE and just commit the correct versions. 

Otherwise everything else looks good. Did you see Alex comment?  ⬇️ 
> Check:
> 
> * [jina-ai/jina#1965](https://github.com/jina-ai/jina/pull/1965)
> * #107
> 
> These fix all 101 links in core and docs repos

If yes: You can **squash and merge.** and celebrate a big open source contribution!

**Review by FionnD — APPROVED** [review]

**Comment by nan-wang** [comment]
@ThePfarrer Many thanks for your marvelous contribution! Would you please help us to solve the conflict?

**Comment by ThePfarrer** [comment]
@nan-wang Done.

**Comment by FionnD** [comment]
@ThePfarrer please fix the last conflict and then merge if you are ready 👍

**Comment by ThePfarrer** [comment]
@FionnD done.

**Comment by FionnD** [comment]
Thank you, can you squash and merge so?

**Pull request merged**
