### PR TITLE
feat: add ranker trainer documentation

### PR DESCRIPTION
**Pull request by bwanglzu**
Add `RankerTrainer` documentation

The documentation is available [here](https://deploy-preview-276--jina-docs.netlify.app/chapters/ranker_trainer/).

### CODE REVIEW

**Comment by nan-wang** [comment]
I suggest adding a section about using the executor in the Flow.

**Comment by bwanglzu** [comment]
@nan-wang added to PR

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by bwanglzu** [comment]
@FionnD @JoanFM can you review when you're available?

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
